maintenace to crud categories
leosbelpoll/vocabuilder pull request #11
Opened 2023-03-18 05:17 UTC by ornoldoacebedo

2023-03-19 15:29 UTC, leosbelpoll requested changes
varios comentarios, generalmente sobre responsabilidad del controlador y servicio, si no te los agarre en el otro crud es porque se van cosas siempre jajaj, por eso hay mas gente que debe de revisar en un equipo real, pero recuerda que lo importante aqui es que entiendas bien el por que y como se hace modo pro

2023-03-19 15:29 UTC, leosbelpoll commented on src/main/java/com/softteam/vocabuilder/controller/CategoryController.java
> +        return new ResponseEntity<Optional<Category>>(optionalCategory, HttpStatus.OK);
aqui este optional lo veo de mas, como que es innecesario, y la idea de tener custom exceptions es que las manejes custom tambien, ejemplo del metodo:

```java
public ResponseEntity<Optional<Category>> getCategory(@PathVariable(value = "id") String id) {
        UUID uuid = UuidUtil.getUUID(id);
        try {
            Category category = categoryService.getCategory(uuid);
            return new ResponseEntity<Category>(category, HttpStatus.OK);
        } catch (ResourceNotFoundException e) {
            return new ResponseEntity<>(e.getMessage(), HttpStatus.NOT_FOUND);
        }
}
```

2023-03-19 15:29 UTC, leosbelpoll commented on src/main/java/com/softteam/vocabuilder/service/CategoryServiceImpl.java
> -            throw new CategoryNotFoundException("category not found",HttpStatus.NOT_FOUND);
esta custom exception esta bien aca, lo que no estaba bien era el httpstatus code, yo lo que no haria una custom exception para cada recurso, sino una general por error, por ejemplo: `ResourceNotFoundException`
```java
throw new ResourceNotFoundException("Category not found");
```
use el concepto general en el comentario del getCategory del controller

2023-03-19 15:29 UTC, leosbelpoll commented on src/main/java/com/softteam/vocabuilder/controller/CategoryController.java
>      }
aqui el delete del controlador tiene demasiada responsabilidades, el no tiene que hacer logica para buscar y si no esta error y si esta mandar a eliminar, el solo tiene que mandar a eliminar, y el servicio tiene que hacer esa logica, ejemplo

```java
public ResponseEntity<Void> deleteCategory(@PathVariable(value = "id") String id) {
        UUID uuid = UuidUtil.getUUID(id);
        try {
            categoryService.deleteCategory(uuid);
            return new ResponseEntity<Void>(HttpStatus.OK);
        }catch (ResourceNotFound e){
            return new ResponseEntity<>(e.getMessage(), HttpStatus.NOT_FOUND);
        }
}
```

2023-03-19 15:29 UTC, leosbelpoll commented on src/main/java/com/softteam/vocabuilder/controller/CategoryController.java
> +    public ResponseEntity<Category> updateCategory(@PathVariable(value = "id") String id, @RequestBody Category category) {
el update tambien tiene demasiada responsabilidad, mira el comentario del eliminar
aqui debes solo mandar a actualizar y toda esa logica encerrarla en un try/catch con ResourceNotFound, y el servicio es el encargado de buscar y si no esta throw ResourceNotFound, y si esta mandar a actualizar con lo que le mandaste aqui en el controller

2023-03-19 15:29 UTC, leosbelpoll commented on src/main/java/com/softteam/vocabuilder/service/dto/CategoryDTO.java
> +    private String color;
a blank line after `id`, and before `@Data` also? 😄 recuerda que hay que tener el codigo lindo jaja

2023-03-19 17:47 UTC, ornoldoacebedo commented on src/main/java/com/softteam/vocabuilder/controller/CategoryController.java
> +        return new ResponseEntity<Optional<Category>>(optionalCategory, HttpStatus.OK);
Lo de la ResourceNotFoundException ya.
con lo del Optional te refieres a que deberia ser solo de tipo Category?Si es el caso, lo que pasa es que el 
`Optional<T> findById(ID id);`
devuelve un Optional entonces me pide que cambie el tipo de variable de Category a Optional<Category>

2023-03-22 19:00 UTC, ornoldoacebedo commented on src/main/java/com/softteam/vocabuilder/controller/CategoryController.java
> +    public ResponseEntity<Category> updateCategory(@PathVariable(value = "id") String id, @RequestBody Category category) {
Resuelto igual que en el caso del delete()

2023-03-28 18:33 UTC, leosbelpoll approved these changes
voy a predonar este PR super largo por el proposito que es jjaja, pero debemos tratar de hacer PR pequennitos

sobre las exceptions, veo que hay dos viviendo juntas `CategoryNotFound` y `ResourceNotFound`, debemos usar solo una, de preferencia la generica para que sirva para todos los cruds, a menos que haga falta agregar alguna super especifica

voy a aprobar el PR, esto lo puedes hacer en otro, para evitar seguir con este

2023-03-28 20:59 UTC, merged